import Head from 'next/head'
import Welcome from '~/components/welcome'

export default function Home() {
	return (
		<>
			<Head>
				<title>Next.js Typescript Jest Chakra-ui template</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main role='main'>
				<Welcome />
			</main>
		</>
	)
}
